name: WT-157

title: &title Component Objects for CWMP

resources:
  specification:
    title: TR-157 Document
  components:
    title: Data Model Components
    restype: components
    resname: *title
  data-model:
    title: Data Model
    restype: root

versions:
  v1.10.1:
    date: 2022-11-15
    status: obsoleted
    editors:
      - Jason Walls, QA Cafe
    changes:
      specification: |
        * Obsoletes TR-157 and adds references to the documents where
          the contents have been moved

  v1.10.0:
    date: 2015-11-09
    status: deprecated
    editors:
      - Tim Carey, Alcatel-Lucent
    changes:
      specification: |
        * Support for HTTP based Bulk Data Collection
      components: |
        * Update Bulk Data Collection for HTTP Transport

  v1.9.0:
    date: 2014-09
    changes:
      components: |
        * Added Inform Parameters table to ManagementServer
        * Added *HTIP* Component to *DeviceInfo* containing HTIP related
          parameters
        * Updated the *UPnP* component for HTIP parameters

  v1.8.0:
    date: 2013-11
    changes:
      components: |
        * Addition of *MS_StandbyPolicy*, *XMPP* and *XMPPConnReq*
          components; other minor updates

  v1.7.0:
    date: 2012-11
    changes:
      components: |
        * Addition of *DNS_SD* component; other minor updates

  v1.6.0:
    date: 2012-05
    changes:
      components: |
        * Addition of *BulkDataCollection* component

  v1.5.0:
    date: 2011-11
    editors:
      - Tim Carey, Alcatel-Lucent
      - Heather Kirksey, Alcatel-Lucent
    changes:
      specification: |
        * Support for Location and Fault Management
      components: |
        * Addition of *Location*, *FaultManagement* and *Security* components

  v1.4.0:
    date: 2011-07
    changes:
      components: |
        * Support for CWMP Proxy Management and Alias-Based Addressing

  v1.3.0:
    date: 2010-11
    editors:
      - John Blackford, Pace
      - Heather Kirksey, Alcatel-Lucent
    changes:
      specification:
        text: |
          * Support for Software Module Management
      components:
        text: |
          * Support for Software Module Management
      data-model:
        resname:
          - InternetGatewayDevice:1.8
          - Device:1.7
        text: |
          * Incorporated new components from [TR-157 Amendment 3]

  v1.2.0:
    date: 2010-05
    editors:
      - John Blackford, 2Wire, Inc.
    changes:
      specification:
        text: |
          * Support for TR-181 Issue 2
      components:
        text: |
          * Support for TR-181 Issue 2
      data-model:
        resname:
          - InternetGatewayDevice:1.7
          - Device:1.6
        text: |
          * Incorporated new components from [TR-157 Amendment 2]

  v1.1.0:
    date: 2009-09
    editors:
      - John Blackford, 2Wire, Inc.
    changes:
      specification:
        text: |
          * Addition of *SupportedDataModel* component
      components:
        text: |
          * Addition of *SupportedDataModel* component
      data-model:
        resname:
          - InternetGatewayDevice:1.6
          - Device:1.4
        text: |
          * Incorporated new components from [TR-157 Amendment 1]

  v1.0.0:
    date: 2009-03
    editors:
      - John Blackford, 2Wire, Inc.
      - Tim Spets, Westell
    changes:
      specification:
        text: |
          * Original
      components:
        text: |
          * Original
      data-model:
        resname:
          - InternetGatewayDevice:1.5
          - Device:1.3
        text: |
          * Incorporated new components from [TR-157 Issue 1]
